# Generated by Django 4.0.5 on 2022-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coin_name_alter_coin_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
