# Generated by Django 4.0.5 on 2022-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_coin_symbol_alter_coin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinhistory',
            name='coin_id',
        ),
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='coinhistory',
            name='symbol',
            field=models.CharField(default='', max_length=5),
        ),
    ]
