# Generated by Django 4.0.5 on 2022-06-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_coinhistory_coin_id_coin_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinhistory',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
    ]
