# Generated by Django 4.0.5 on 2022-06-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coinhistory_symbol_alter_coin_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin'),
        ),
    ]
