# Generated by Django 4.0.5 on 2022-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coin_symbol_alter_coinhistory_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='symbol',
            field=models.CharField(default='', max_length=5),
        ),
    ]
