# Generated by Django 4.0.5 on 2022-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_coin_symbol_alter_coinhistory_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhistory',
            name='date',
            field=models.DateField(),
        ),
    ]
